### ISSUE TITLE
Works fine on localhost and http, but doesn't work with HTTPS

### ISSUE THREAD

**Issue by elliotkoss** [jaredhanson/passport-ethereum#1]
First, let me thank you @jaredhanson for all the great work you've done getting Passport to be such a useful set of modules (apologies if I'm minimizing the library of tools you've built).

I love that you built something for Ethereum, and given that it's only been about 2 weeks since release, there probably haven't been enough people working on it to run into these issues.

Heads up: This took me 12+ hrs to figure out, and to be honest, I'm not sure what the proper solution should be. But the source of the problem is in how `tls` is defined in the utils.js file.

This works fine in localhost and http. But when trying to access from https, I was constantly receiving a 403 Authorization Error, URI Mismatch. I thought this was something I had done, so I read all the documentation (like 5 times), tested all my code, and still couldn't identify the source. At first, I didn't even realize that http worked - I learned that by accident.

When I started playing with the module (around the 10th hour), that's when things started to click.

It's the logic for how `tls` is defined that seems to continue to default my Heroku server with SSL (when I'm hitting the https URL) to http which creates the URI Mismatch since https != http.

This is what I did to fix it on my end (had to bring this out from being a module and instead make it my own directory). 

I hope that this is useful. Please let me know when you've resolved this. I don't know much about the technical details of http vs https, so I'm not sure if my solution is fully secure.

Thanks again for what you've built!

<img width="645" alt="image" src="https://user-images.githubusercontent.com/5436129/175119919-6e3c1db5-ab3d-49f0-8fd8-6c5359d58e90.png">

**Comment by jaredhanson** [comment]
When running on Heroku, SSL is being terminated by Heroku's routing layer and communication between Heroku and your app is occurring via HTTP.   To get your Express app to trust the`X-Forwarded-*` headers from Heroku's proxy, you enable the `trust proxy` setting in your app:

```
app.enable('trust proxy')
```

Read this for more information: https://expressjs.com/en/guide/behind-proxies.html


Let me know if enabling that solves your issue.   Editing the utils file in the way you did is dangerous, as it allows untrusted entities to set `X-Forwarded-Proto` headers claiming HTTPS is in use when it is not.

**Comment by elliotkoss** [comment]
Thank you! I just added the app.enable line and it worked. Of course it was a simple one-line change.

I figured that my change was probably not the right thing (I was touching parts of the code that I don't really understand), so thanks for the quick reply so that I could fix this.
